Problem6 Solution
trishnaguha/projecteulersolution pull request #4
Opened 2017-03-25 14:32 UTC by ntkathole

2017-03-25 14:37 UTC, trishnaguha commented
Thanks for the PR @ntkathole . Mind designing it object oriented way?

2017-03-25 16:57 UTC, ntkathole reviewed
Added object oriented approach

2017-03-26 03:37 UTC, trishnaguha requested changes

2017-03-26 03:37 UTC, trishnaguha commented on solutions/prob6.py
> +        	self.number = number
Could you please follow [PEP8](https://www.python.org/dev/peps/pep-0008/) rules? 
You will need to modify indentation, naming convention of class, variables, add spaces.

2017-03-26 03:40 UTC, trishnaguha requested changes

2017-03-26 03:40 UTC, trishnaguha commented on solutions/prob6.py
> +	def sum(self):
It is suggested not to use any built-in names in Python.

2017-03-26 03:41 UTC, trishnaguha requested changes

2017-03-26 03:41 UTC, trishnaguha commented on solutions/prob6.py
> +			sum1=sum1+i
You can do sum1 += i?
I would prefer to use some other variable instead of `sum1`.

2017-03-26 03:42 UTC, trishnaguha requested changes

2017-03-26 03:42 UTC, trishnaguha commented on solutions/prob6.py
> +        	self.number = number
Change the argument name `number` to `endrange` or something? `number` is kind of confusing.

2017-03-26 03:44 UTC, trishnaguha requested changes

2017-03-26 03:44 UTC, trishnaguha commented on solutions/prob6.py
> +		N = self.number
`endrange` is constant here. You do not need to assign the `endrange` to a variable. 
We should keep memory management in mind when writing code :-).

2017-03-26 03:45 UTC, trishnaguha requested changes

2017-03-26 03:45 UTC, trishnaguha commented on solutions/prob6.py
> +		print(self.square(self.sum())-self.sumofsquares())
Use `return` here. We can print when calling the function with the object.

2017-03-26 03:46 UTC, trishnaguha requested changes

2017-03-26 03:46 UTC, trishnaguha commented on solutions/prob6.py
> +        	N = self.number
Follow [review](https://github.com/trishnaguha/projecteulersolution/pull/4/files#r108051215) .

2017-03-27 12:39 UTC, ntkathole reviewed
updated changes

2017-03-28 03:35 UTC, trishnaguha requested changes

2017-03-28 03:35 UTC, trishnaguha commented on solutions/prob6.py
> +import math
The code does not follow PEP8 rules yet.

2017-03-28 06:28 UTC, ntkathole reviewed
Thanks for reviews...formatted according to PEP8

2017-03-29 04:08 UTC, trishnaguha commented
Merging it :-).

2017-03-29 04:08 UTC, merged